export const EVENT_STATE_CHANGED = '@ws/event/STATE_CHANGED';
export const RESULT_GET_STATES_SUCCESS = '@ws/result/GET_STATES_SUCCESS';
export const RESULT_MEDIA_PLAYER_THUMBNAIL_SUCCESS = '@ws/result/MEDIA_PLAYER_THUMBNAIL_SUCCESS';
