export const AUTHENTICATION_REQUEST = '@auth/AUTHENTICATION_REQUEST';
export const AUTHENTICATION_SUCCESS = '@auth/AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_FAILURE = '@auth/AUTHENTICATION_FAILURE';
